// Generated by CoffeeScript 1.6.3
(function() {
  var utils;

  utils = {
    noop: function() {},
    check: function(name, pointer, type) {
      if (pointer && typeof pointer === type) {
        return;
      }
      throw new Error("" + name + " " + type + " is required.");
    },
    log: function() {
      var a;
      return console.log(((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = arguments.length; _i < _len; _i++) {
          a = arguments[_i];
          _results.push(a.toString());
        }
        return _results;
      }).apply(this, arguments)).join(", "));
    }
  };

  module.exports = utils;

}).call(this);
