// Generated by CoffeeScript 1.6.3
(function() {
  var core, fs, log, path, reactor, utile,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  fs = require("fs");

  path = require("path");

  utile = require("utile");

  log = require("../common/utils").log;

  core = ["index.js", "reactor.js"];

  reactor = function(godot) {
    var file, method, name, parts, _i, _len, _ref;
    _ref = fs.readdirSync(__dirname);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      file = _ref[_i];
      if (!(__indexOf.call(core, file) < 0 && (path.extname(file)) === ".js")) {
        continue;
      }
      name = file.replace(/.js$/, "");
      parts = name.split("-");
      method = parts[0];
      if (parts.length > 1) {
        method += utile.capitalize(parts[1]);
      }
      log("loading reactor " + name);
      godot[method] = require("./" + name);
    }
  };

  module.exports = reactor;

}).call(this);
